apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: fuy13301w-go 
  janus-idp.io/tekton: fuy13301w-go
  backstage.io/kubernetes-id: fuy13301w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fuy13301w-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  