apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: fuy13301w-go
  janus-idp.io/tekton: fuy13301w-go
  backstage.io/kubernetes-id: fuy13301w-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: fuy13301w-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
