apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: fuy13301w-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fuy13301w-go 
  name: fuy13301w-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: fuy13301w-go 
